//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookTrackingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int OStudentID { get; set; }
        public Nullable<int> OTeacherID { get; set; }
        public Nullable<int> OAdminID { get; set; }
        public int OBookID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> OClassID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
